# Generated by Django 6.1 on 2026-10-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_userprofile_department_alter_userprofile_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_cost_centers', to='employees.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_cost_centers', to='employees.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cost_centers', to='organization.costcenter')),
                ('deputy_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deputy_manager', to='employees.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_manager', to='employees.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cost_centers', to='organization.costcenter')),
                ('deputy_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deputy_manager', to='employees.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_manager', to='employees.userprofile')),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.directorate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_cost_centers', to='organization.costcenter')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_manager', to='employees.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cost_centers', to='organization.costcenter')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='organization.department')),
                ('deputy_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deputy_manager', to='employees.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_manager', to='employees.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.organization')),
            ],
        ),
        migrations.AddField(
            model_name='directorate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directorates', to='organization.site'),
        ),
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_departments', to='organization.site'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cost_centers', to='organization.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_units', to='organization.department')),
                ('deputy_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deputy_manager', to='employees.userprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_manager', to='employees.userprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='organization.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
