# Generated by Django 6.1 on 2026-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.CharField(choices=[('varna', 'VARNA'), ('burgas', 'BURGAS')], default='VARNA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('facility_management', 'Facility Management'), ('procurement', 'Procurement'), ('accountant', 'Accountant'), ('terminal_management', 'Terminal Management'), ('appron_services', 'Appron Services'), ('passenger_services', 'Passenger Services'), ('human_resources', 'Human Resources'), ('security', 'Security'), ('safety', 'Safety'), ('aoc', 'AOC'), ('it', 'IT')], max_length=100),
        ),
    ]
