# Generated by Django 6.1 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_userprofile_site_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Facility Management', 'Facility Management'), ('Procurement', 'Procurement'), ('Accountant', 'Accountant'), ('Terminal Management', 'Terminal Management'), ('Apron Services', 'Appron Services'), ('Passenger Services', 'Passenger Services'), ('Human Resources', 'Human Resources'), ('Security', 'Security'), ('Safety', 'Safety'), ('AOC', 'AOC'), ('IT', 'IT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.CharField(choices=[('VAR', 'VAR'), ('BOJ', 'BOJ')], max_length=50),
        ),
    ]
